num1 = int(input("enter first number: "))
num2 = int(input("enter second number: " ))
num3 = int(input("enter third number: "))
num4 = int(input("enter fourth number: "))
num5 = int(input("enter fifth number: "))
num6 = int(input("enter sixth number: "))
num7 = int(input("enter seventh number: "))
num8 = int(input("enter eighth number: "))
num9 = int(input("enter ninth number: "))
num10 = int(input("enter tenth number: "))
print(num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10)


word1 = input("enter first word: ")
word2 = input("enter second word: ")
word3 = input("enter third word: ")
print(word1 + " " + word2  + " " + word3 )

number = int(input("enter number"))
print(number + 5)