print(True and False or not False and False)
print(False and True and not True or False)
print((20>18) or not True  and False or (30<21))
print(True and False or False or not True or not False)
print((30/3<13) or (21<20))
print((27*2/4>30)and True or not False)
print((30>20) and (23*2<20) or not True or (13*2/3<13))
print(True and not False or False or not True or (13>4) or False (22/11>1))
print(True or False and True)
print(True and not True or False or True)